### ISSUE TITLE
Can HmmUFOtu be used on non bacterial taxa?

### ISSUE THREAD

**Issue by jshleap** [Grice-Lab/HmmUFOtu#3]
Hello! I would like to test your implementation on a wider range of taxa beyond bacterial and with different markers. Can HmmUFOtu handle this assuming I construct the trees with BL optimized?

Best,

Sergio #

**Comment by e00011027** [comment]
Hi Sergio,

Theoretically yes. The only limitation now is the consensus length cannot
greater than 65535 (short int). Please let me know your results.

Best
Qi
